<?php
/**
* Implements hook_form_alter. */
function forcontu_forms_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  switch($form_id) {
    case 'system_site_information_settings':
      $form['site_information']['site_slogan']['#required'] = TRUE;
    break;
    case 'node_page_form':
      case 'node_page_edit_form':
        $form['options']['#open'] = TRUE;
        // Añade el elemento highlighted
        $form['options']['highlighted'] = [ '#type' => 'checkbox',
        '#title' => t('Highlighted'), '#weight' => 100,
        ];
      break;
  }
}

function forcontu_forms_system_site_information_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['site_information']['site_slogan']['#required'] = TRUE;
}

function forcontu_forms_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['options']['#open'] = TRUE;
  $form['options']['highlighted'] = [
    '#type' => 'checkbox',
    '#title' => t('Highlighted'),
    '#weight' => 100,
  ];
}
